version = 1

exclude_patterns = [
  "node_modules",
  ".next",
  ".github",
  ".husky",
  ".vscode",
  "pnpm-lock.yaml",
  "packages/graphql/generated.ts"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
